# Generated by Django 5.2.8 on 2025-11-28 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Selecione...', 'Selecione...'), ('Smartfones', 'Smartfones'), ('Notebooks', 'Notebooks'), ('SmartTV', 'SmartTV')], default='Selecione...', max_length=15)),
                ('quantidade_estoque', models.BigIntegerField()),
                ('preco', models.FloatField()),
                ('descricao', models.TextField()),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produtos', models.BigIntegerField()),
                ('tipo_movimentacao', models.CharField(choices=[('Selecione...', 'Selecione...'), ('Entrada', 'Entrada'), ('Saída', 'Saída')], default='Selecione...', max_length=15)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoLucas_app.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Historicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_historico', models.DateField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnoLucas_app.produtos')),
            ],
        ),
    ]
