# Generated by Django 5.2.8 on 2025-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoLucas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='tipo',
            field=models.CharField(choices=[('Selecione...', 'Selecione...'), ('Smartfone', 'Smartfone'), ('Notebook', 'Notebook'), ('SmartTV', 'SmartTV')], default='Selecione...', max_length=15),
        ),
    ]
