# Generated by Django 5.2.8 on 2025-12-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoLucas_app', '0002_alter_usuarios_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterModelTable(
            name='historicos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='movimentacoes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='produtos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
